### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by ghost** [zabbix-byte/PyPulse#18]
I'm trying to install ```python-pulse``` so i can connect to the api but its not installing the dependency

**Comment by ghost** [comment]
![Screen Shot 2024-11-02 at 6 10 20 PM](https://github.com/user-attachments/assets/76e8bf7c-dfa6-407e-94e2-78b7047472c2)

**Comment by zabbix-byte** [comment]
@spinGreekGod, What version of Python are you using? Try creating a clean virtual environment for that version to keep it isolated.

Check if you already have these libraries installed with different versions:

- wxPython==4.2.1
- Jinja2==3.1.2
- cefpython3==66.1

If they’re installed with other versions, consider updating or creating a virtual environment to manage dependencies.
